<a href="https://colab.research.google.com/github/jim-junior/deep_learning_course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu121


# Introduction to Tensors

Creating tensors


In [4]:
# Scalar

scalar = torch.tensor(1)
scalar

tensor(1)

In [5]:
vector = torch.tensor([1,3])

vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
scalar.shape

torch.Size([])

In [9]:
MATRIX = torch.tensor([
    [1, 3, 4],
    [1, 3, 5]
])

MATRIX.ndim

2

A tensor can be of any amount of dimensions

## Random Tensors

Why?

Random tensors are iportant because the way many neural networks learn if by starting with a random sent of numbers and then adjust those random numbers to better represent the data

In [12]:
# Creating random tensors

random = torch.rand(3, 4)
random

tensor([[0.7385, 0.5521, 0.0998, 0.2345],
        [0.9073, 0.8020, 0.2013, 0.5114],
        [0.7826, 0.2333, 0.7231, 0.7940]])

In [14]:
random.ndim

2

In [15]:
random.shape

torch.Size([3, 4])

In [16]:
torch.rand(size=(3, 244, 244))

tensor([[[0.8109, 0.4415, 0.8803,  ..., 0.7929, 0.9166, 0.9012],
         [0.6791, 0.4282, 0.9876,  ..., 0.9708, 0.1692, 0.6461],
         [0.9613, 0.0112, 0.2653,  ..., 0.6669, 0.9747, 0.0409],
         ...,
         [0.0833, 0.4085, 0.4357,  ..., 0.3997, 0.2188, 0.5728],
         [0.8227, 0.0957, 0.2692,  ..., 0.0308, 0.5433, 0.3964],
         [0.6049, 0.4634, 0.6035,  ..., 0.3008, 0.9224, 0.6406]],

        [[0.0936, 0.8037, 0.5169,  ..., 0.8828, 0.1849, 0.8865],
         [0.5304, 0.2404, 0.5286,  ..., 0.6258, 0.6541, 0.5036],
         [0.6636, 0.3519, 0.5761,  ..., 0.4207, 0.6664, 0.6065],
         ...,
         [0.1968, 0.4821, 0.2087,  ..., 0.9578, 0.7833, 0.5593],
         [0.8393, 0.1731, 0.5421,  ..., 0.7652, 0.9046, 0.3881],
         [0.5694, 0.1542, 0.9508,  ..., 0.6053, 0.7514, 0.2501]],

        [[0.4299, 0.4949, 0.4217,  ..., 0.6020, 0.6260, 0.9557],
         [0.1794, 0.3636, 0.1710,  ..., 0.2033, 0.1642, 0.7448],
         [0.3853, 0.4339, 0.9230,  ..., 0.3131, 0.0368, 0.

## Zeros and Ones

In [18]:
zeros = torch.zeros(
    3, 4
)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating a range of tensors and tensors like

In [19]:
torch.arange(0, 5)

tensor([0, 1, 2, 3, 4])

In [20]:
# step
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [21]:
# Creating tensors like

initial = torch.rand(3, 4)

zeros_like = torch.zeros_like(initial)
zeros_like

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros_like.shape, zeros_like.ndim, initial.ndim

(torch.Size([3, 4]), 2, 2)

## Tensor data types

why they matter?
because with different data types it enables to trade between precession and computational speed.

its also important to consider data types because errors usually occur due to
- Tensors not right data types
- Tensors not right shape
- Or tensors are not on the right device


In [24]:
# Example

t = torch.tensor(
    [1, 3, 4],
    dtype=torch.float32,
    device=None, requires_grad=False)

In [25]:
# changing type
t16 = t.type(torch.float16)
t16

tensor([1., 3., 4.], dtype=torch.float16)

In [26]:
t * t16

tensor([ 1.,  9., 16.])

In [27]:
t.dtype

torch.float32

In [28]:
t.device

device(type='cpu')

## Tensor Operations