<a href="https://colab.research.google.com/github/jim-junior/deep_learning_course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cpu


# Introduction to Tensors

Creating tensors


In [2]:
# Scalar

scalar = torch.tensor(1)
scalar

tensor(1)

In [3]:
vector = torch.tensor([1,3])

vector.ndim

1

In [4]:
vector.shape

torch.Size([2])

In [5]:
scalar.shape

torch.Size([])

In [6]:
MATRIX = torch.tensor([
    [1, 3, 4],
    [1, 3, 5]
])

MATRIX.ndim

2

A tensor can be of any amount of dimensions

## Random Tensors

Why?

Random tensors are iportant because the way many neural networks learn if by starting with a random sent of numbers and then adjust those random numbers to better represent the data

In [7]:
# Creating random tensors

random = torch.rand(3, 4)
random

tensor([[0.7591, 0.9803, 0.3052, 0.6015],
        [0.5246, 0.9914, 0.0781, 0.8393],
        [0.4153, 0.4525, 0.5472, 0.0580]])

In [8]:
random.ndim

2

In [9]:
random.shape

torch.Size([3, 4])

In [10]:
torch.rand(size=(3, 244, 244))

tensor([[[0.3027, 0.0819, 0.9705,  ..., 0.4294, 0.3502, 0.3159],
         [0.6867, 0.7458, 0.6613,  ..., 0.5105, 0.1391, 0.5770],
         [0.0918, 0.9923, 0.4102,  ..., 0.9352, 0.3466, 0.4984],
         ...,
         [0.8461, 0.4224, 0.8288,  ..., 0.4086, 0.0593, 0.1188],
         [0.4768, 0.7061, 0.5130,  ..., 0.4508, 0.0788, 0.3349],
         [0.1063, 0.2790, 0.4052,  ..., 0.3249, 0.1625, 0.2504]],

        [[0.7244, 0.3892, 0.4363,  ..., 0.2011, 0.9375, 0.3981],
         [0.3168, 0.9607, 0.6303,  ..., 0.5853, 0.1218, 0.1070],
         [0.4697, 0.4148, 0.5525,  ..., 0.8373, 0.7475, 0.2872],
         ...,
         [0.6303, 0.8860, 0.3727,  ..., 0.3209, 0.9967, 0.5475],
         [0.4441, 0.3772, 0.0935,  ..., 0.6457, 0.3473, 0.3434],
         [0.3360, 0.6521, 0.7111,  ..., 0.4725, 0.1671, 0.3351]],

        [[0.9170, 0.8714, 0.8587,  ..., 0.7001, 0.0597, 0.5534],
         [0.1987, 0.8159, 0.9109,  ..., 0.0728, 0.4701, 0.5743],
         [0.9798, 0.2544, 0.7639,  ..., 0.4869, 0.3031, 0.

## Zeros and Ones

In [11]:
zeros = torch.zeros(
    3, 4
)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating a range of tensors and tensors like

In [12]:
torch.arange(0, 5)

tensor([0, 1, 2, 3, 4])

In [13]:
# step
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [14]:
# Creating tensors like

initial = torch.rand(3, 4)

zeros_like = torch.zeros_like(initial)
zeros_like

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
zeros_like.shape, zeros_like.ndim, initial.ndim

(torch.Size([3, 4]), 2, 2)

## Tensor data types

why they matter?
because with different data types it enables to trade between precession and computational speed.

its also important to consider data types because errors usually occur due to
- Tensors not right data types
- Tensors not right shape
- Or tensors are not on the right device


In [16]:
# Example

t = torch.tensor(
    [1, 3, 4],
    dtype=torch.float32,
    device=None, requires_grad=False)

In [17]:
# changing type
t16 = t.type(torch.float16)
t16

tensor([1., 3., 4.], dtype=torch.float16)

In [18]:
t * t16

tensor([ 1.,  9., 16.])

In [19]:
t.dtype

torch.float32

In [20]:
t.device

device(type='cpu')

## Tensor Operations

In [21]:
t * 10

tensor([10., 30., 40.])

In [22]:
t + 10

tensor([11., 13., 14.])

In [23]:
t

tensor([1., 3., 4.])

### Matrix Multiplication

In [24]:
# Element wise multiplication
t * t

tensor([ 1.,  9., 16.])

In [25]:
# Matrix multiplication
torch.matmul(t, t)

tensor(26.)

In [26]:
t1 = torch.rand(2, 3)
t2 = torch.rand(3, 2)
t1, t2

(tensor([[0.8705, 0.2082, 0.8594],
         [0.1203, 0.9124, 0.9031]]),
 tensor([[0.4514, 0.0701],
         [0.3464, 0.3856],
         [0.1885, 0.5002]]))

In [27]:
torch.matmul(t1, t2)

tensor([[0.6270, 0.5712],
        [0.5406, 0.8120]])

One of the most common errors in deep learning is shape error

There are two main rules when performing matrix multiplication

1. The inner dimenssions must match
  - `(3, 2) @ (3, 2)` wont work
  - `(2, 3) @ (3, 2)` will work
  - `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the outer dimensions
  - `(2, 3) @ (3, 2)` -> `(2, 2)`

To fix out shape issues, we can manipulate on of the tensors using a transpose

A transpose switches the axes or dimensions of a given tensor

In [28]:
# tensor.T stands for the transpose
t1.T, t1

(tensor([[0.8705, 0.1203],
         [0.2082, 0.9124],
         [0.8594, 0.9031]]),
 tensor([[0.8705, 0.2082, 0.8594],
         [0.1203, 0.9124, 0.9031]]))

In [29]:
t1.T.shape, t1.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## Reshaping, stacking, squeezing and unsqueezing tensors

- Reshape: reshapes and input tensor to a defined shape
- View: Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
- Stack: combine tensors on top of each other. Either vertically (vstack) or horizontally (hstack)
- Squeeze: remove all `1` dimensions from a tensor
- Unsqueeze: add `1` dimensions to a tensor
- Permute: Return a view of an imput tensor with dimensions swaped in a certain way